# Generated by Django 3.0.4 on 2020-03-07 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.PositiveIntegerField(choices=[(1, 'super_admin'), (2, 'admin'), (3, 'employee'), (4, 'banned')], primary_key=True, serialize=False, verbose_name='ROLE ID')),
            ],
        ),
    ]
