# Generated by Django 3.0.4 on 2020-03-07 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='id',
            field=models.PositiveIntegerField(choices=[(1, 'Super Admin'), (2, 'Admin'), (3, 'Employee'), (4, 'Banned')], primary_key=True, serialize=False, verbose_name='ROLE ID'),
        ),
    ]
