# Generated by Django 3.0.4 on 2020-03-22 07:36

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20200309_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='height',
            field=models.IntegerField(blank=True, null=True, verbose_name='Height'),
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(height_field='height', max_length=500, null=True, upload_to=user.models.image_upload_path, verbose_name='Image', width_field='width'),
        ),
        migrations.AddField(
            model_name='user',
            name='width',
            field=models.IntegerField(blank=True, null=True, verbose_name='Width'),
        ),
    ]
